/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { trpc } from "../utils/trpc"; // tRPC hook

const Home: NextPage = () => {
  // fetch pokemon from backend
  const [pokemon, setPokemon]: any = useState();
  const fetchPokemon = async () => {
    const res = await fetch("http://localhost:3000/api/pokemon");
    const data = await res.json();
    setPokemon(data);
  };

  const hello = trpc.useQuery(["hello"]);

  const handleClick = () => {
    console.log(pokemon[0].id);
  };

  useEffect(() => {
    fetchPokemon();
  }, []);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>
          {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading...</p>}
        </div>
        <button onClick={handleClick}>Click me</button>

        {pokemon?.map((pokemon: any) => (
          <div key={pokemon.id}>
            <h1>{pokemon.pokemonName}</h1>
            <img src={pokemon.pokemonImage} alt={pokemon.pokemonName} />
          </div>
        ))}
      </div>
    </>
  );
};

export default Home;
