import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  // fetch pokemon from backend
  const [pokemon, setPokemon]: any = useState();
  const fetchPokemon = async () => {
    const res = await fetch("http://localhost:3000/api/pokemon");
    const data = await res.json();
    console.log(data);
    setPokemon(data);
  };

  const handleClick = () => {
    console.log(pokemon[0].id);
  };

  useEffect(() => {
    fetchPokemon();
  }, []);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={handleClick}>Click me</button>
      <div>
        {pokemon.map((pokemon: any) => (
          <div key={pokemon.id}>
            <h1>{pokemon.pokemonName}</h1>
            <img src={pokemon.pokemonImage} alt={pokemon.pokemonName} />
          </div>
        ))}
      </div>
    </>
  );
};

export default Home;
